version: '3.8'
services:
  postgres_db:
    container_name: 'budgettest'
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=larlarlar
    ports:
      - '5432:5432'
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: budgettest
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db