spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/budget
    username: postgres
    password: larlarlar
    driverClassName: org.postgresql.Driver
  data:
    mongodb:
      database: budget
server:
  servlet:
    context-path: "/api"
currency:
  rates:
    url: https://www.bnr.ro/nbrfxrates.xml
    scheduler:
      cron: 0 0 0 * * *